# CodeRabbit Configuration
# Documentation: https://docs.coderabbit.ai/configuration/

# Review settings
reviews:
  enabled: true
  review_all_files: true
  # Force review even if other bots detected (if supported)
  review_status: true

# Paths to exclude from review
exclude_paths:
  - "**/node_modules/**"
  - "**/venv/**"
  - "**/.venv/**"
  - "**/__pycache__/**"
  - "**/.pytest_cache/**"
  - "**/build/**"
  - "**/dist/**"
  - "**/.next/**"
  - "**/coverage/**"
  - "**/*.min.js"
  - "**/*.bundle.js"
  - "**/migrations/**"
  - "**/package-lock.json"
  - "**/yarn.lock"

# Suggestions settings
suggestions:
  enabled: true
  auto_apply: false
  min_confidence: 0.7

# Chat settings
chat:
  enabled: true
  respond_to_comments: true
