# CodeRabbit Configuration
# Documentation: https://docs.coderabbit.ai/configuration/
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# Review settings
reviews:
  enabled: true
  review_all_files: true

# Chat settings
chat:
  enabled: true
  respond_to_comments: true
